# config for epsilon greedy qlearning

program: qlearning.py
method: grid
name: epsilon_sweep
metric:
  goal: maximize
  name: average_return

parameters:
  step_size: 
    values: [0.001, 0.01, 0.1]
  
  epsilon:
    values: [0.01, 0.05, 0.1, 0.2]

  gamma:
    value: 0.99

