# config for epsilon greedy qlearning

program: tabular/tabular_qlearning_tile_count.py
method: grid
name: tile_count_sweep
metric:
  goal: maximize
  name: average_return

parameters:
  step_size: 
    values: [0.001, 0.01, 0.1]
  
  epsilon:
    values: [0.01, 0.05, 0.1, 0.2]

  beta:
    values: [10, 100, 1000, 10000]

  gamma:
    value: 0.99

